spring.datasource.url=${DB_URL:jdbc:postgresql://ep-wild-shape-aoua4u9c-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require}
spring.datasource.username=${DB_USERNAME:neondb_owner}
spring.datasource.password=${DB_PASSWORD:npg_Ex0a9dvZwYRS}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Config
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Flyway config
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=1
spring.flyway.locations=classpath:db/migration/{vendor}

# JWT Settings
jwt.secret=${JWT_SECRET_KEY:default-very-long-secret-key-32-chars-long-or-more-for-hs256-hashing-security-12345}
# Access Token expiry: 24h = 86400 seconds
jwt.expiration-seconds=86400
# Refresh Token expiry: 7 days = 604800000 milliseconds
jwt.refresh-token-expiration=604800000

# Logging
logging.level.com.hotelbooking=DEBUG
logging.level.org.springframework.security=INFO

# Payment Integration
payment.gateway.secret=${PAYMENT_GATEWAY_SECRET:mock-gateway-secret-key-that-is-long-enough-for-hs256-hashing-1234567890}

# Flyway Repair
spring.flyway.repair-on-migrate=true
