-- V30__Extend_payment_and_voucher_features.sql (PostgreSQL)

CREATE TABLE IF NOT EXISTS payouts (
    payout_id BIGSERIAL PRIMARY KEY,
    user_id BIGINT REFERENCES users(user_id) ON DELETE CASCADE,
    amount DECIMAL(18,2) NOT NULL,
    status VARCHAR(30) DEFAULT 'PENDING',
    bank_account VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE payouts ADD COLUMN IF NOT EXISTS user_id BIGINT REFERENCES users(user_id) ON DELETE CASCADE;
ALTER TABLE payouts ADD COLUMN IF NOT EXISTS amount DECIMAL(18,2);
ALTER TABLE payouts ADD COLUMN IF NOT EXISTS status VARCHAR(30) DEFAULT 'PENDING';
ALTER TABLE payouts ADD COLUMN IF NOT EXISTS bank_account VARCHAR(100);
ALTER TABLE payouts ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE payments ADD COLUMN IF NOT EXISTS gateway_ref VARCHAR(255);

CREATE INDEX IF NOT EXISTS idx_payouts_user ON payouts(user_id);
