-- V8__Add_booking_and_payment_columns.sql
-- Description: Add support columns and create room_locks table for booking flow (PostgreSQL)

-- Add confirmed_at and notes to bookings table
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS confirmed_at TIMESTAMP NULL;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS notes TEXT NULL;

-- Add transaction_id to payments table
ALTER TABLE payments ADD COLUMN IF NOT EXISTS transaction_id VARCHAR(255) NULL;

-- Create room_locks table
CREATE TABLE IF NOT EXISTS room_locks (
    lock_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id BIGINT NOT NULL,
    booking_id BIGINT NOT NULL,
    locked_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_room_locks_room FOREIGN KEY (room_id) REFERENCES rooms(room_id),
    CONSTRAINT fk_room_locks_booking FOREIGN KEY (booking_id) REFERENCES bookings(booking_id)
);

CREATE INDEX IF NOT EXISTS idx_room_locks_room_id ON room_locks(room_id);
CREATE INDEX IF NOT EXISTS idx_room_locks_booking_id ON room_locks(booking_id);
