-- V9__Online_payment_and_voucher.sql
-- Description: Thêm các bảng và cột cho tính năng Online Payment, Hoàn tiền (SPEC-034) và Voucher (SPEC-035) (PostgreSQL)

-- 1. SPEC-013 & SPEC-034 & SPEC-035: Cập nhật cấu trúc bảng bookings và payments
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS payment_status VARCHAR(50) DEFAULT 'PENDING';
ALTER TABLE payments ADD COLUMN IF NOT EXISTS gateway VARCHAR(50);
ALTER TABLE payments ADD COLUMN IF NOT EXISTS payment_time TIMESTAMP;

-- Tạo index unique cho transaction_id
CREATE UNIQUE INDEX IF NOT EXISTS idx_payments_transaction_id ON payments(transaction_id) WHERE transaction_id IS NOT NULL;

-- 2. SPEC-034: Thêm cột cho hoàn tiền vào payments
ALTER TABLE payments ADD COLUMN IF NOT EXISTS refund_amount DECIMAL(18,2);
ALTER TABLE payments ADD COLUMN IF NOT EXISTS refund_time TIMESTAMP;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS refund_status VARCHAR(50);
ALTER TABLE payments ADD COLUMN IF NOT EXISTS refund_transaction_id VARCHAR(100);
ALTER TABLE payments ADD COLUMN IF NOT EXISTS refund_retry_count INT DEFAULT 0;

-- 3. SPEC-035: Tạo bảng vouchers
CREATE TABLE IF NOT EXISTS vouchers (
    voucher_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    discount_type VARCHAR(20) NOT NULL, -- PERCENTAGE, FIXED_AMOUNT
    discount_value DECIMAL(18,2) NOT NULL,
    min_booking_value DECIMAL(18,2) DEFAULT 0,
    start_date TIMESTAMP,
    end_date TIMESTAMP,
    max_usage INT DEFAULT 0, -- 0 means unlimited
    current_usage INT DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_vouchers_code ON vouchers(code);

-- 4. SPEC-035: Thêm cột voucher cho bookings
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS voucher_id BIGINT;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS discount_amount DECIMAL(18,2) DEFAULT 0;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS final_price DECIMAL(18,2);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_bookings_voucher') THEN
        ALTER TABLE bookings ADD CONSTRAINT fk_bookings_voucher FOREIGN KEY (voucher_id) REFERENCES vouchers(voucher_id);
    END IF;
END $$;

-- 5. Tạo bảng payment_audit_logs
CREATE TABLE IF NOT EXISTS payment_audit_logs (
    log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id VARCHAR(100),
    action VARCHAR(100) NOT NULL,
    request_payload TEXT,
    response_payload TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_payment_audit_logs_transaction_id ON payment_audit_logs(transaction_id);

-- Cập nhật final_price cho các booking cũ
UPDATE bookings SET final_price = total_amount WHERE final_price IS NULL;
